import type { Metadata } from "next";
import { Fredoka, Quicksand } from "next/font/google";
import "./style/globals.css";

const qeistFredoka = Fredoka({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistQuickSand = Quicksand({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BookSprouts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${qeistFredoka.variable} ${geistQuickSand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
